- hosts: localhost
  tasks:
    - name: Run DevOps container
      docker_container:
        name: devops_app
        image: devops_app
        state: started
        ports:
          - "5000:5000"
        restart_policy: always